steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/word-game-socket-backend', '.' ]

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${_PROJECT_ID}/word-game-socket-backend' ]

images:
  - 'gcr.io/${_PROJECT_ID}/word-game-socket-backend'
